### ISSUE TITLE
Tensorboard logs are not showing in HF Hub

### ISSUE THREAD

**Issue by fcakyon** [huggingface/hub-docs#632]
I can see the tensorboard scalar charts in my local correctly, but they are not showing in HF Hub. How could I fix it?

Buggy HF Hub tensorboard page: https://huggingface.co/keremberke/yolov8s-forklift-detection/tensorboard
Related discussion: https://discuss.huggingface.co/t/possible-bug-in-hf-hub-tensorboard-logs-not-showing/30149

I started using the great tensorboard feature of the hub after seeing one of @merveenoyan's posts 🚀 Maybe she can help me with this 🤗

**Comment by merveenoyan** [comment]
thanks a lot @fcakyon for letting us know, indeed I managed to reproduce it with another repository: https://huggingface.co/merve/vq-vae/tensorboard doesn't appear on older models but with the ones that we upload recently @severo

**Comment by XciD** [comment]
We had an issue with event on tensorboard this week-end, it's solved now

**Comment by XciD** [comment]
Yes, we are recovering all misses events. Should be done by now

**Comment by nickcharles** [comment]
This seems like it's an ongoing issue, Tensorboard charts seem to load only intermittently.

**Comment by julien-c** [comment]
@severo @rtrompier

**Comment by YusuphaJuwara** [comment]
Yes, I am also having the same issue right now. When should we expect a fix? As somebody already mentioned above, it seems to be working for some and not others! 

Here is a link to a repo, where I tried to play with different setups. But none works! https://huggingface.co/YusuphaJuwara/nli-fever-v2/tensorboard

Note that I'll delete the repo soon, since it was only for testing!

Looking forward to a fix soon! Thank you!

**Comment by severo** [comment]
Hmmm, could you share the dataset again? For the two datasets mentioned in https://github.com/huggingface/hub-docs/issues/632#issuecomment-1407712108, the tensorboard traces are empty (the file only contains 40 bytes: https://huggingface.co/keremberke/yolov8m-pothole-segmentation/tree/main and https://huggingface.co/keremberke/yolov8m-table-extraction/tree/main)

**Comment by severo** [comment]
I think it's fixed now. Closing.

**Comment by YusuphaJuwara** [comment]
Thanks! It works now! Love your HF!

**Comment by JeffersonQin** [comment]
Seems the issue is still there. The link provided still cannot see any data:

https://huggingface.co/keremberke/yolov8m-table-extraction/tensorboard
https://huggingface.co/keremberke/yolov8m-pothole-segmentation/tensorboard

I am also coming across this issue myself.

**Comment by severo** [comment]
Also here: https://discuss.huggingface.co/t/tensorboard-does-not-load-on-hub-loads-locally-tfevents-files-are-uploaded-to-hub/74917/4

**Comment by olivierr42** [comment]
I am also experiencing this issue.
